spring:
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  config:
    import: optional:classpath:application-secrets.yml
  ai:
    openai:
      base-url: https://api.groq.com/openai # 내부 서버를 groq으로
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
          temperature: 0

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
server:
  port: 8080