kakao:
  client_id: a273ba33d7a1c94dca58ba1d17b93829
  redirect_uri: http://localhost:8080/oauth/kakao

jwt:
  secret-key: mySecretKeyForJWTTokenGenerationAndValidation1234567890
  access-token-validity: 86400000
  refresh-token-validity: 604800000