spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data: #RedisTemplate 등을 사용하기 위한 직접 연결용
    redis:
      host: 10.0.1.246
      port: 6379
      timeout: 6000
      password: zoopzoopRedisTest!
  cache: #Spring Cache를 사용하기 위한 Redis
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

sentry:
  dsn: https://60f1acad189d2994353d59b7895076ee@o4510100579155968.ingest.us.sentry.io/4510100584923136
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  environment: prod
  traces-sample-rate: 0.2
