spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data: #RedisTemplate 등을 사용하기 위한 직접 연결용
    redis:
      host: localhost
      port: 6379
      timeout: 6000

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

app:
  seed:
    enabled: true

front:
  redirect_domain: http://localhost:3000

sentry:
  send-default-pii: true
  environment: local
  traces-sample-rate: 0.0

liveblocks:
  secret-key: test_dummy_liveblocks_secret_key
