spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data: #RedisTemplate 등을 사용하기 위한 직접 연결용
    redis:
      host: 10.0.1.246
      port: 6379
      timeout: 6000
      password: ${redis-password-test}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://api.test.zoopzoop.kro.kr/login/oauth2/code/kakao
          google:
            redirect-uri: https://api.test.zoopzoop.kro.kr/login/oauth2/code/google

front:
  redirect_domain: http://localhost:3000

sentry:
  send-default-pii: true
  environment: prod-server
  traces-sample-rate: 0.2

liveblocks:
  secret-key: test_dummy_liveblocks_secret_key


