spring:
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  config:
    import: optional:classpath:application-secrets.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      base-url: https://api.groq.com/openai # 내부 서버를 groq으로
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
          temperature: 0
  data: #RedisTemplate 등을 사용하기 위한 직접 연결용
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  cache: #Spring Cache를 사용하기 위한 Redis
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
      key-prefix:
  rabbitmq: # RabbitMQ 연결 설정
    host: ${SPRING_RABBITMQ_HOST:localhost} # 환경 변수(SPRING_RABBITMQ_HOST)가 있으면 그 값을 쓰고, 없으면 기본값(localhost)을 사용
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
    org.springframework.retry: DEBUG

server:
  port: 8080

app:
  seed:
    enabled: true